var views_8py =
[
    [ "CourseModuleUpdateView", "classcourses_1_1views_1_1_course_module_update_view.html", "classcourses_1_1views_1_1_course_module_update_view" ],
    [ "OwnerMixin", "classcourses_1_1views_1_1_owner_mixin.html", "classcourses_1_1views_1_1_owner_mixin" ],
    [ "OwnerEditMixin", "classcourses_1_1views_1_1_owner_edit_mixin.html", "classcourses_1_1views_1_1_owner_edit_mixin" ],
    [ "OwnerCourseMixin", "classcourses_1_1views_1_1_owner_course_mixin.html", null ],
    [ "OwnerCourseEditMixin", "classcourses_1_1views_1_1_owner_course_edit_mixin.html", null ],
    [ "ManageCourseListView", "classcourses_1_1views_1_1_manage_course_list_view.html", null ],
    [ "CourseCreateView", "classcourses_1_1views_1_1_course_create_view.html", null ],
    [ "CourseUpdateView", "classcourses_1_1views_1_1_course_update_view.html", null ],
    [ "CourseDeleteView", "classcourses_1_1views_1_1_course_delete_view.html", null ],
    [ "ContentCreateUpdateView", "classcourses_1_1views_1_1_content_create_update_view.html", "classcourses_1_1views_1_1_content_create_update_view" ],
    [ "ContentDeleteView", "classcourses_1_1views_1_1_content_delete_view.html", "classcourses_1_1views_1_1_content_delete_view" ],
    [ "ModuleContentListView", "classcourses_1_1views_1_1_module_content_list_view.html", "classcourses_1_1views_1_1_module_content_list_view" ],
    [ "ModuleOrderView", "classcourses_1_1views_1_1_module_order_view.html", "classcourses_1_1views_1_1_module_order_view" ],
    [ "ContentOrderView", "classcourses_1_1views_1_1_content_order_view.html", "classcourses_1_1views_1_1_content_order_view" ],
    [ "SubjectListView", "classcourses_1_1views_1_1_subject_list_view.html", null ],
    [ "CourseListView", "classcourses_1_1views_1_1_course_list_view.html", "classcourses_1_1views_1_1_course_list_view" ],
    [ "CourseDetailView", "classcourses_1_1views_1_1_course_detail_view.html", "classcourses_1_1views_1_1_course_detail_view" ],
    [ "dispatch", "views_8py.html#a0eea71301b59232165bbef6159806ed9", null ],
    [ "get", "views_8py.html#a0116da6af6fff0adda47b64ed33c9ad7", null ],
    [ "post", "views_8py.html#a0c8ff98ee5c4241ad9082dea024a1801", null ],
    [ "model", "views_8py.html#a16fd560e1a06d18179b5f18c51e13672", null ],
    [ "module", "views_8py.html#a1f707cad47821c8366f3ee4d2d86bd01", null ],
    [ "obj", "views_8py.html#a80d0102109b3ec86c3f90fdd2553e80f", null ]
];